"""
ProtocolAdvisory Repository Implementation (ADR-037).

Concrete implementation of IProtocolAdvisoryRepository using SQLAlchemy ORM.
Manages persistence and querying of protocol advisories generated by the
Analysis Engine for the Protocol Engine.

Following project patterns:
- Extends BaseRepository for session management and error handling
- Multi-tenant scoping via fermentation_id (winery context inherited)
- Structured logging with LogTimer (ADR-027)
- Returns ORM entities directly (no DTO mapping)
- Async operations with SQLAlchemy
"""
from datetime import datetime, timezone
from typing import List, Optional
from uuid import UUID

from sqlalchemy import and_, select, func, desc

from src.shared.wine_fermentator_logging import get_logger, LogTimer
from src.shared.infra.repository.base_repository import BaseRepository
from src.modules.analysis_engine.src.domain.repositories.protocol_advisory_repository_interface import (
    IProtocolAdvisoryRepository,
)
from src.modules.analysis_engine.src.domain.entities.protocol_advisory import ProtocolAdvisory
from src.modules.analysis_engine.src.domain.enums.advisory_type import AdvisoryType
from src.modules.analysis_engine.src.domain.enums.risk_level import RiskLevel

logger = get_logger(__name__)


class ProtocolAdvisoryRepository(BaseRepository, IProtocolAdvisoryRepository):
    """
    Repository for ProtocolAdvisory data operations.

    Implements IProtocolAdvisoryRepository using SQLAlchemy ORM with
    BaseRepository infrastructure for session management and error mapping.
    """

    async def add(self, advisory: ProtocolAdvisory) -> ProtocolAdvisory:
        """Persist a new ProtocolAdvisory."""
        async def _operation():
            with LogTimer(logger, "add_protocol_advisory"):
                logger.info(
                    "creating_protocol_advisory",
                    fermentation_id=str(advisory.fermentation_id),
                    analysis_id=str(advisory.analysis_id),
                    advisory_type=advisory.advisory_type,
                    risk_level=advisory.risk_level,
                )
                session_cm = await self.get_session()
                async with session_cm as session:
                    session.add(advisory)
                    await session.flush()
                    logger.info(
                        "protocol_advisory_created",
                        advisory_id=str(advisory.id),
                        risk_level=advisory.risk_level,
                    )
                    return advisory

        return await self.execute_with_error_mapping(_operation)

    async def add_many(self, advisories: List[ProtocolAdvisory]) -> List[ProtocolAdvisory]:
        """Persist multiple advisories in one flush."""
        if not advisories:
            return []

        async def _operation():
            with LogTimer(logger, "add_many_protocol_advisories"):
                logger.info(
                    "creating_protocol_advisories_batch",
                    count=len(advisories),
                    fermentation_id=str(advisories[0].fermentation_id),
                )
                session_cm = await self.get_session()
                async with session_cm as session:
                    for advisory in advisories:
                        session.add(advisory)
                    await session.flush()
                    logger.info(
                        "protocol_advisories_batch_created",
                        count=len(advisories),
                    )
                    return advisories

        return await self.execute_with_error_mapping(_operation)

    async def get_by_id(self, advisory_id: UUID) -> Optional[ProtocolAdvisory]:
        """Retrieve an advisory by primary key."""
        async def _operation():
            with LogTimer(logger, "get_protocol_advisory_by_id"):
                session_cm = await self.get_session()
                async with session_cm as session:
                    stmt = select(ProtocolAdvisory).where(
                        ProtocolAdvisory.id == advisory_id
                    )
                    result = await session.execute(stmt)
                    return result.scalar_one_or_none()

        return await self.execute_with_error_mapping(_operation)

    async def get_by_fermentation_id(
        self,
        fermentation_id: UUID,
        include_acknowledged: bool = True,
        skip: int = 0,
        limit: int = 50,
    ) -> List[ProtocolAdvisory]:
        """List all advisories for a fermentation, most recent first."""
        async def _operation():
            with LogTimer(logger, "get_advisories_by_fermentation"):
                session_cm = await self.get_session()
                async with session_cm as session:
                    conditions = [ProtocolAdvisory.fermentation_id == fermentation_id]
                    if not include_acknowledged:
                        conditions.append(ProtocolAdvisory.is_acknowledged == False)  # noqa: E712

                    stmt = (
                        select(ProtocolAdvisory)
                        .where(and_(*conditions))
                        .order_by(desc(ProtocolAdvisory.created_at))
                        .offset(skip)
                        .limit(limit)
                    )
                    result = await session.execute(stmt)
                    return list(result.scalars().all())

        return await self.execute_with_error_mapping(_operation)

    async def get_by_analysis_id(self, analysis_id: UUID) -> List[ProtocolAdvisory]:
        """List advisories generated for a specific analysis run."""
        async def _operation():
            with LogTimer(logger, "get_advisories_by_analysis"):
                session_cm = await self.get_session()
                async with session_cm as session:
                    stmt = (
                        select(ProtocolAdvisory)
                        .where(ProtocolAdvisory.analysis_id == analysis_id)
                        .order_by(desc(ProtocolAdvisory.created_at))
                    )
                    result = await session.execute(stmt)
                    return list(result.scalars().all())

        return await self.execute_with_error_mapping(_operation)

    async def get_unacknowledged_by_fermentation_id(
        self,
        fermentation_id: UUID,
    ) -> List[ProtocolAdvisory]:
        """
        List pending advisories for a fermentation, sorted by risk level (critical first).
        """
        async def _operation():
            with LogTimer(logger, "get_unacknowledged_advisories"):
                session_cm = await self.get_session()
                async with session_cm as session:
                    stmt = (
                        select(ProtocolAdvisory)
                        .where(
                            and_(
                                ProtocolAdvisory.fermentation_id == fermentation_id,
                                ProtocolAdvisory.is_acknowledged == False,  # noqa: E712
                            )
                        )
                        .order_by(desc(ProtocolAdvisory.created_at))
                    )
                    result = await session.execute(stmt)
                    advisories = list(result.scalars().all())

                    # Sort in Python by risk priority (CRITICAL first)
                    advisories.sort(
                        key=lambda a: RiskLevel(a.risk_level).priority_score,
                        reverse=True,
                    )
                    return advisories

        return await self.execute_with_error_mapping(_operation)

    async def acknowledge(self, advisory_id: UUID) -> Optional[ProtocolAdvisory]:
        """Mark an advisory as acknowledged by the winemaker."""
        async def _operation():
            with LogTimer(logger, "acknowledge_protocol_advisory"):
                logger.info(
                    "acknowledging_protocol_advisory",
                    advisory_id=str(advisory_id),
                )
                session_cm = await self.get_session()
                async with session_cm as session:
                    stmt = select(ProtocolAdvisory).where(
                        ProtocolAdvisory.id == advisory_id
                    )
                    result = await session.execute(stmt)
                    advisory = result.scalar_one_or_none()

                    if advisory is None:
                        logger.warning(
                            "protocol_advisory_not_found",
                            advisory_id=str(advisory_id),
                        )
                        return None

                    advisory.acknowledge()
                    await session.flush()

                    logger.info(
                        "protocol_advisory_acknowledged",
                        advisory_id=str(advisory_id),
                        acknowledged_at=advisory.acknowledged_at.isoformat(),
                    )
                    return advisory

        return await self.execute_with_error_mapping(_operation)

    async def list_by_risk_level(
        self,
        fermentation_id: UUID,
        risk_level: RiskLevel,
        skip: int = 0,
        limit: int = 50,
    ) -> List[ProtocolAdvisory]:
        """List advisories filtered by risk level for a fermentation."""
        async def _operation():
            session_cm = await self.get_session()
            async with session_cm as session:
                stmt = (
                    select(ProtocolAdvisory)
                    .where(
                        and_(
                            ProtocolAdvisory.fermentation_id == fermentation_id,
                            ProtocolAdvisory.risk_level == risk_level.value,
                        )
                    )
                    .order_by(desc(ProtocolAdvisory.created_at))
                    .offset(skip)
                    .limit(limit)
                )
                result = await session.execute(stmt)
                return list(result.scalars().all())

        return await self.execute_with_error_mapping(_operation)

    async def list_by_advisory_type(
        self,
        fermentation_id: UUID,
        advisory_type: AdvisoryType,
        skip: int = 0,
        limit: int = 50,
    ) -> List[ProtocolAdvisory]:
        """List advisories filtered by advisory type for a fermentation."""
        async def _operation():
            session_cm = await self.get_session()
            async with session_cm as session:
                stmt = (
                    select(ProtocolAdvisory)
                    .where(
                        and_(
                            ProtocolAdvisory.fermentation_id == fermentation_id,
                            ProtocolAdvisory.advisory_type == advisory_type.value,
                        )
                    )
                    .order_by(desc(ProtocolAdvisory.created_at))
                    .offset(skip)
                    .limit(limit)
                )
                result = await session.execute(stmt)
                return list(result.scalars().all())

        return await self.execute_with_error_mapping(_operation)

    async def count_unacknowledged(self, fermentation_id: UUID) -> int:
        """Count pending advisories for a fermentation (for UI badge counts)."""
        async def _operation():
            session_cm = await self.get_session()
            async with session_cm as session:
                stmt = select(func.count(ProtocolAdvisory.id)).where(
                    and_(
                        ProtocolAdvisory.fermentation_id == fermentation_id,
                        ProtocolAdvisory.is_acknowledged == False,  # noqa: E712
                    )
                )
                result = await session.execute(stmt)
                return result.scalar_one()

        return await self.execute_with_error_mapping(_operation)
