"""
ProtocolAdvisory entity - Advisory generated by Analysis Engine for Protocol Engine.

When the Analysis Engine detects anomalies, it generates a ProtocolAdvisory
suggesting adjustments to the active protocol execution. This is the core
entity of ADR-037 Phase 3: Analysis Output → Protocol Advisory.

Following project pattern: Entity = ORM Model (inherits from Base).
No cross-module ORM relationships: fermentation/protocol IDs stored as plain UUIDs.
"""
from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4

from sqlalchemy import String, Float, Boolean, DateTime, Index
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.shared.infra.orm.base_entity import Base
from ..enums.advisory_type import AdvisoryType
from ..enums.risk_level import RiskLevel


class ProtocolAdvisory(Base):
    """
    Advisory generated by the Analysis Engine for the Protocol Engine.

    Represents a suggestion to adjust the active protocol execution based
    on anomalies detected during fermentation analysis.

    ADR-037 Design Decisions:
    - No cross-module ORM FK to ProtocolExecution (ADR-035 pattern: module independence)
    - execution_id stored as plain UUID (auditable but not ORM-linked)
    - is_acknowledged / acknowledged_at for winemaker dismissal workflow (ADR-037 Phase 5)
    - suggestion + reasoning stored as strings for transparency

    Lifecycle:
        CREATED → displayed in UI → winemaker acknowledges/dismisses
    """

    __tablename__ = "protocol_advisory"
    __table_args__ = (
        Index("ix_protocol_advisory_fermentation_id", "fermentation_id"),
        Index("ix_protocol_advisory_analysis_id", "analysis_id"),
        Index("ix_protocol_advisory_advisory_type", "advisory_type"),
        Index("ix_protocol_advisory_risk_level", "risk_level"),
        Index("ix_protocol_advisory_is_acknowledged", "is_acknowledged"),
        Index("ix_protocol_advisory_created_at", "created_at"),
        {"extend_existing": True},
    )

    # Primary key
    id: Mapped[PGUUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4
    )

    # Cross-module references (plain UUIDs — no ORM FK per ADR-035 pattern)
    fermentation_id: Mapped[PGUUID] = mapped_column(
        PGUUID(as_uuid=True), nullable=False
    )
    analysis_id: Mapped[PGUUID] = mapped_column(
        PGUUID(as_uuid=True), nullable=False
    )
    execution_id: Mapped[Optional[PGUUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )

    # Advisory classification
    advisory_type: Mapped[str] = mapped_column(String(50), nullable=False)
    target_step_type: Mapped[str] = mapped_column(String(100), nullable=False)
    risk_level: Mapped[str] = mapped_column(String(50), nullable=False)

    # Suggestion content
    suggestion: Mapped[str] = mapped_column(String(500), nullable=False)
    reasoning: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    # Confidence from Analysis Engine [0.0 - 1.0]
    confidence: Mapped[float] = mapped_column(Float, nullable=False)

    # Winemaker acknowledgement (ADR-037 Phase 5)
    is_acknowledged: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    def __init__(
        self,
        fermentation_id=None,
        analysis_id=None,
        advisory_type=None,
        target_step_type=None,
        risk_level=None,
        suggestion=None,
        confidence=None,
        execution_id=None,
        reasoning=None,
        is_acknowledged=False,
        acknowledged_at=None,
        created_at=None,
        id=None,
    ):
        self.id = id or uuid4()
        self.fermentation_id = fermentation_id
        self.analysis_id = analysis_id
        self.execution_id = execution_id

        # Accept enum instances or raw strings
        self.advisory_type = (
            advisory_type.value
            if isinstance(advisory_type, AdvisoryType)
            else advisory_type
        )
        self.target_step_type = (
            target_step_type.value
            if hasattr(target_step_type, "value")
            else target_step_type
        )
        self.risk_level = (
            risk_level.value if isinstance(risk_level, RiskLevel) else risk_level
        )

        self.suggestion = suggestion
        self.reasoning = reasoning
        self.confidence = confidence

        self.is_acknowledged = is_acknowledged
        self.acknowledged_at = acknowledged_at
        self.created_at = created_at or datetime.now(timezone.utc)

    # ------------------------------------------------------------------
    # Accessors
    # ------------------------------------------------------------------

    @property
    def advisory_type_enum(self) -> AdvisoryType:
        """Return advisory_type as AdvisoryType enum."""
        return AdvisoryType(self.advisory_type)

    @property
    def risk_level_enum(self) -> RiskLevel:
        """Return risk_level as RiskLevel enum."""
        return RiskLevel(self.risk_level)

    @property
    def is_critical(self) -> bool:
        """True if this advisory requires immediate action."""
        return self.risk_level == RiskLevel.CRITICAL.value

    def acknowledge(self) -> None:
        """Mark advisory as acknowledged by the winemaker."""
        self.is_acknowledged = True
        self.acknowledged_at = datetime.now(timezone.utc)

    def to_dict(self) -> dict:
        """Serialize to dict (for logging / API responses)."""
        return {
            "id": str(self.id),
            "fermentation_id": str(self.fermentation_id),
            "analysis_id": str(self.analysis_id),
            "execution_id": str(self.execution_id) if self.execution_id else None,
            "advisory_type": self.advisory_type,
            "target_step_type": self.target_step_type,
            "risk_level": self.risk_level,
            "suggestion": self.suggestion,
            "reasoning": self.reasoning,
            "confidence": self.confidence,
            "is_acknowledged": self.is_acknowledged,
            "acknowledged_at": (
                self.acknowledged_at.isoformat() if self.acknowledged_at else None
            ),
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return (
            f"<ProtocolAdvisory id={self.id} "
            f"type={self.advisory_type} step={self.target_step_type} "
            f"risk={self.risk_level} conf={self.confidence:.2f}>"
        )
