"""ADR-037: Create protocol_advisory table (Mar 15, 2026)

Revision ID: 003_create_protocol_advisory_table
Revises: 002_create_protocol_alerts_table
Create Date: 2026-03-15

Creates 1 new table for Protocol-Analysis Integration (ADR-037):
- protocol_advisory: Advisories generated by the Analysis Engine
  when anomalies indicate the active protocol should be adjusted.

Schema matches ProtocolAdvisory entity exactly:
    src/modules/analysis_engine/src/domain/entities/protocol_advisory.py

Advisory lifecycle: CREATED → displayed in UI → winemaker acknowledges/dismisses

Design notes:
- Uses UUID primary key (Analysis Engine uses UUIDs throughout)
- fermentation_id, analysis_id, execution_id are plain UUIDs with no
  ORM FK — cross-module independence per ADR-035 pattern
- advisory_type: ACCELERATE_STEP | SKIP_STEP | ADD_STEP
- risk_level: CRITICAL | HIGH | MEDIUM | LOW
- Indices optimized for: fermentation lookup, risk filtering, unack'd queue
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = "003_protocol_advisory"
down_revision: Union[str, None] = "002_create_protocol_alerts_table"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Create protocol_advisory table
    # Stores advisories generated by Analysis Engine → Protocol Engine (ADR-037)
    op.create_table(
        'protocol_advisory',

        # Primary key (UUID — consistent with Analysis Engine conventions)
        sa.Column(
            'id', UUID(as_uuid=True), nullable=False,
            server_default=sa.text('gen_random_uuid()'),
            comment='Advisory UUID',
        ),

        # Cross-module references (plain UUIDs, no FK — module independence ADR-035)
        sa.Column(
            'fermentation_id', UUID(as_uuid=True), nullable=False,
            comment='Fermentation UUID (no FK — cross-module independence)',
        ),
        sa.Column(
            'analysis_id', UUID(as_uuid=True), nullable=False,
            comment='Analysis UUID that triggered this advisory',
        ),
        sa.Column(
            'execution_id', UUID(as_uuid=True), nullable=True,
            comment='Active ProtocolExecution UUID (optional, for traceability)',
        ),

        # Advisory classification
        sa.Column(
            'advisory_type', sa.String(length=50), nullable=False,
            comment='ACCELERATE_STEP | SKIP_STEP | ADD_STEP',
        ),
        sa.Column(
            'target_step_type', sa.String(length=100), nullable=False,
            comment='Protocol step category to act on (e.g. H2S_CHECK, MONITORING)',
        ),
        sa.Column(
            'risk_level', sa.String(length=50), nullable=False,
            comment='CRITICAL | HIGH | MEDIUM | LOW',
        ),

        # Suggestion content
        sa.Column(
            'suggestion', sa.String(length=500), nullable=False,
            comment='Human-readable advisory text shown to winemaker',
        ),
        sa.Column(
            'reasoning', sa.String(length=1000), nullable=True,
            comment='Detailed explanation of why this advisory was generated',
        ),

        # Confidence from Analysis Engine [0.0 - 1.0]
        sa.Column(
            'confidence', sa.Float(), nullable=False,
            comment='Advisory confidence score [0.0 - 1.0]',
        ),

        # Winemaker acknowledgement workflow (ADR-037 Phase 5)
        sa.Column(
            'is_acknowledged', sa.Boolean(), nullable=False,
            server_default='false',
            comment='True once winemaker has reviewed/dismissed this advisory',
        ),
        sa.Column(
            'acknowledged_at', sa.DateTime(timezone=True), nullable=True,
            comment='Timestamp when winemaker acknowledged this advisory',
        ),

        # Timestamps
        sa.Column(
            'created_at', sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text('NOW()'),
            comment='Timestamp when advisory was generated',
        ),

        sa.PrimaryKeyConstraint('id', name='pk_protocol_advisory'),
    )

    # Indices — optimized for the main query patterns
    # 1. "Show all advisories for this fermentation" (most frequent)
    op.create_index(
        'ix_protocol_advisory_fermentation_id',
        'protocol_advisory',
        ['fermentation_id'],
    )
    # 2. "Which analysis generated this advisory" (traceability)
    op.create_index(
        'ix_protocol_advisory_analysis_id',
        'protocol_advisory',
        ['analysis_id'],
    )
    # 3. "Filter by advisory type" (e.g. only ACCELERATE_STEP)
    op.create_index(
        'ix_protocol_advisory_advisory_type',
        'protocol_advisory',
        ['advisory_type'],
    )
    # 4. "Filter by risk level" (e.g. only CRITICAL)
    op.create_index(
        'ix_protocol_advisory_risk_level',
        'protocol_advisory',
        ['risk_level'],
    )
    # 5. "Unacknowledged advisory queue" (winemaker dashboard)
    op.create_index(
        'ix_protocol_advisory_is_acknowledged',
        'protocol_advisory',
        ['is_acknowledged'],
    )
    # 6. "Recent advisories first" (default sort order)
    op.create_index(
        'ix_protocol_advisory_created_at',
        'protocol_advisory',
        ['created_at'],
    )


def downgrade() -> None:
    # Drop indices first, then table
    op.drop_index('ix_protocol_advisory_created_at', table_name='protocol_advisory')
    op.drop_index('ix_protocol_advisory_is_acknowledged', table_name='protocol_advisory')
    op.drop_index('ix_protocol_advisory_risk_level', table_name='protocol_advisory')
    op.drop_index('ix_protocol_advisory_advisory_type', table_name='protocol_advisory')
    op.drop_index('ix_protocol_advisory_analysis_id', table_name='protocol_advisory')
    op.drop_index('ix_protocol_advisory_fermentation_id', table_name='protocol_advisory')
    op.drop_table('protocol_advisory')
